Initial Configuration for the Extension
uchen-ml/codeart-binexplore pull request #2
Opened 2024-08-16 08:47 UTC by aharbii

- Configuring Extension package, and structure
- Configuring required environment
- Configuring vscode workspace, settings, tasks, and debugger.
- Configuring extension icon
   * extracted from "https://uchenml.tech/" SVG logo

- Configuring GTS [Google TypeScript] style guide, formatter, and linter.
- Configuring ESLint to enforce style guide, and provide automated fixes
- Configuring Prettier to re-format code

- Configuring GitHub Actions:
    - On Pull Requests:
        - Adding labels
        - Added fake main.cpp file with CMake configuration to build on different OS, to be used later for testing,
          and GitHub Actions
        - Build the extension on linux 
           * without calling vscode extension test as it requires display which is not provided on the server
        - Build the extension on macOS with pre-configuration for running tests
        * Build on windows is consuming much time than other processes - To be discussed if how required is it
     - On main branch update:
        - All actions from Pull Request
        - Generating a new release for the extension

- Implementing:
   - ReadOnly viewer to be opened, once the user opens an executable file showing placeholder 'Lorem Ipsum'
   - Logic for checking if the opened file is executable
      * as objdump can also be run for object files, and system libraries, to be discussed if it's sufficient
        to only generate reports for executables, or other files can be considered
   * Noticed UI/UX uncomfortable drawback - when the user opens an executable on vscode
      there's a warning page mentioning 
      'The file is not displayed in the text editor because it is either binary or uses an unsupported text encoding.'

      vscode APIs cannot detect that the user opens a binary before the user selects 'Open Anyway' option,
      then the extension logic get fired.

- Tested on:
   - Linux - Ubuntu 20.04
   - macOS Sequoia Developer's Beta - Apple Silicon
   - Windows 11

2024-08-17 05:25 UTC, eugeneo requested changes
Thank you, this is great and really close to the first milestone!

One comment is that it opens two editors (see the screenshot). Can it be made to only open the one with "Lorem Ipsium"?

<img width="875" alt="editors" src="https://github.com/user-attachments/assets/e3de28c1-3d15-4dfb-a326-8cbab55513ca">

2024-08-17 05:25 UTC, eugeneo commented on README.md
>  VSCode extension for analyzing compiled binaries
Feel free to add checkout instructions and basic info on how to use the plugin.

2024-08-17 05:25 UTC, eugeneo commented on src/extension.ts
> +  if (!fs.existsSync(filePath)) {
`Sync` method will block on the main JS thread and result in a bad user experience. Please use promise-based API with `async`/`exec`

2024-08-17 05:25 UTC, eugeneo commented on src/extension.ts
> +    const stats = fs.statSync(filePath);
`Sync` should not be used in UI applications, only in command line tools.

2024-08-17 05:25 UTC, eugeneo commented on src/extension.ts
> +    return isExecutable || isWinExecutable;
We specifically do not support Windows executable. For now, just allow any executable on any OS.

2024-08-17 05:25 UTC, eugeneo commented on src/extension.ts
> +    console.error(error);
Avoid `console` calls. They are not helpful for users and mask the errors. I think removing `catch` and allowing the exception escape will be fine here. We can better decide how to handle that later.

2024-08-17 05:25 UTC, eugeneo commented on src/preview.ts
> +  private _onDidChange = new vscode.EventEmitter<vscode.Uri>();
No need to start the private field with an underscore - it is already private. See `content` on the line below.

2024-08-17 05:25 UTC, eugeneo commented on src/preview.ts
> +    .then(
Do not use `.then`, always use `async`/`await`. It makes exceptions easier to handle and the code is more readable.

2024-08-17 05:25 UTC, eugeneo commented on src/preview.ts
> +  vscode.workspace.openTextDocument(uri).then(document => {
It is `then` again, also the promise is "dangling" - in that the "previewOutput" will exit before the call to `showTextDocument` completes. I am not familiar with VS Code enough, but in my experience this often ends up messing the user experince (e.g. editor opens not where expected because focus moved, some error dialog pops up, etc.)

2024-08-17 05:25 UTC, eugeneo commented on src/test/objectFilesGenerator/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.12)
IMHO, it's fine just to check in a prebuilt executable to use as a test data. Building the executable on the platform that runs the test may break the tests on some platforms or cause the tests to flake. Some minimum executable or even an object file with one function should be enough.

2024-08-17 05:25 UTC, eugeneo commented on .eslintrc.json
> +  "extends": "./node_modules/gts/"
I usually also set these (apologies for single quote, I copied it from another project):
```suggestion
  "extends": "./node_modules/gts/"
  "rules": {
        "object-curly-spacing": ["error", "always"],
        "require-jsdoc": "off",
        'valid-jsdoc': 'off',
        'prettier/prettier': 'error',
        '@typescript-eslint/no-unused-vars': 'warn',
        '@typescript-eslint/no-floating-promises': 'error',
    },
```

This is my previous project settings, feel free to copy if that works: [uchen-ml/github-sampler@.eslintrc.js](https://github.com/uchen-ml/github-sampler/blob/main/.eslintrc.js)

2024-08-17 16:24 UTC, aharbii commented
Something like closing the actual binary editor, and open the CodeArt editor only? or you mean to not split the view?

2024-08-17 17:50 UTC, eugeneo commented
On second thought, lets keep the current behavior. Please address the code comments and I will approve this PR and the first milestone.

2024-08-17 18:54 UTC, aharbii commented on src/extension.ts
> +    return isExecutable || isWinExecutable;
ok, I will remove isWinExecutable logic, but the extension will not be usable at all for any windows application

2024-08-17 18:55 UTC, aharbii commented on src/extension.ts
> +    console.error(error);
I can add a new output channel in vscode, to log the errors, and any additional data which could be useful for issues reporting, and debugging

2024-08-17 18:58 UTC, eugeneo commented
That’s fine. Windows support is not a priority at this time. I expect
supporting Windows will be a significant effort and most users use Visual
Studio anyways.

On Sat, Aug 17, 2024 at 11:55 AM Ahmed Harbi ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/extension.ts
> <https://github.com/uchen-ml/codeart-binexplore/pull/2#discussion_r1720818467>
> :
>
> > + * @param filePath The path to the file.
> + * @returns True if the file is a binary executable, false otherwise.
> + */
> +function isExecutable(filePath: string): boolean {
> +  if (!fs.existsSync(filePath)) {
> +    return false;
> +  }
> +
> +  try {
> +    const stats = fs.statSync(filePath);
> +
> +    const isExecutable = (stats.mode & 0o111) !== 0;
> +    const isWinExecutable =
> +      filePath.endsWith('.exe') && os.platform() === 'win32';
> +
> +    return isExecutable || isWinExecutable;
>
> ok, I will remove isWinExecutable logic, but the extension will not be
> usable at all for any windows application
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/uchen-ml/codeart-binexplore/pull/2#discussion_r1720818467>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACGJLOEPRAIG33BJVWEEF3ZR6MAXAVCNFSM6AAAAABMTVHRO6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENBUGEZTMNRSGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-08-17 18:59 UTC, eugeneo commented
Sure. Do what you believe makes sense.

On Sat, Aug 17, 2024 at 11:56 AM Ahmed Harbi ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/extension.ts
> <https://github.com/uchen-ml/codeart-binexplore/pull/2#discussion_r1720818681>
> :
>
> > + */
> +function isExecutable(filePath: string): boolean {
> +  if (!fs.existsSync(filePath)) {
> +    return false;
> +  }
> +
> +  try {
> +    const stats = fs.statSync(filePath);
> +
> +    const isExecutable = (stats.mode & 0o111) !== 0;
> +    const isWinExecutable =
> +      filePath.endsWith('.exe') && os.platform() === 'win32';
> +
> +    return isExecutable || isWinExecutable;
> +  } catch (error) {
> +    console.error(error);
>
> I can add a new output channel in vscode, to log the errors, and any
> additional data which could be useful for issues reporting, and debugging
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/uchen-ml/codeart-binexplore/pull/2#discussion_r1720818681>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACGJLISJXZNSQN6YJM63QLZR6MEBAVCNFSM6AAAAABMTVHRO6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENBUGEZTMNZUG4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-08-17 18:59 UTC, aharbii commented on src/test/objectFilesGenerator/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.12)
ok, can do that, I just added the logic to build the executable, considering future contriubition for the extension development, as the prebuild executables will be limited to the currently used environment. Any contributor working on different environment ["Win32", "Intel Based macOS", "ARM based windows, and linux"] will need to recompile the test files, and generate new executables

2024-08-17 19:42 UTC, eugeneo commented on src/test/objectFilesGenerator/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.12)
Will discuss this more when we get to that part of the project.

2024-08-17 19:43 UTC, eugeneo commented on src/extension.ts
> +    console.error(error);
Sure. Do what you believe makes sense.

2024-08-17 20:22 UTC, aharbii commented on README.md
>  VSCode extension for analyzing compiled binaries
planning to that when providing the second milestone, as it will provide some vscode workspace settings for objdump path and args, and some images to be used for demo

2024-08-17 20:39 UTC, aharbii commented
Resolved review findings.

To be resolved:
- Using CMake to generate the executables, and binaries
    - to be discussed more when we get to that part of the project
- Updating README.md
    - to be updated as per milestones, as the planned changes will includes vscode settings for objdump path and args
    - when we hit the second milestone, the preview results will include actual objdump results which can be used as images in README.md

New features:
- added output channel to include all of the extensions logs, information, and to be used later for debugging, and issues reporting.

2024-08-18 18:32 UTC, eugeneo approved these changes

2024-08-18 18:32 UTC, eugeneo commented on src/extension.ts
> +    await fs.promises.access(filePath, fs.constants.F_OK);
I don't think there's a need to do both `access` and `stat`. Stat will detect a missing file.

2024-08-18 18:34 UTC, merged