Adding objdump execution logic
uchen-ml/codeart-binexplore pull request #21
Opened 2024-08-22 14:18 UTC by aharbii

Documentation: 
- Adding README.md initial configurations
- Adding demo assets to be used in README.md

Featurs:
- Adding objdump execution logic
    - in case of error, the error value to be logged to the output channel
    - preview editor will not be shown, and the user will get notified to check the output pannel
- Adding objdump path configuration logic
    - When the user updates the configurtation, a validation logic get fired to check that:
        - objdump path is valid and exists
        - the selected objdump path is an actual binary exceutable
        - it's a valid objdump binary not just any binary by mistake, by runnig objdump --help, and compare the result with expected valid output
        - the user can only configure this configuration as 'objdump' and the logic to fetch objdump executable from  system path
        - in case of any error, the extension resets this configuration to 'objdump' and fetch the executable from 'objdump' path 
    - default value is 'objdump'
- Adding objdump options configuration logic
    - a text box where the user can add required options to be passed to objdump
    - validation logic for such a logic is not yet clear, as there's several inputs --> To be discussed
    - default value is '-d -S'
- Updating preview panel to view objdump raw output
- Updating preview panel to be viewed in the same column as the active editor
    - if the actual binary is opened on the second column for example, the behavior was not user friendly
- Updating output panel to now be shown by default on startup to avoid annoying the user, it will only be force shown in case of errors

Testing:
- Adding test cases for dumper.ts logic
- Adding initial test cases for the extension GUI
    - There's an issue with the automated extension test cases for the extension logic as we need to open an executable and there's no known way to bypass vscode warning for opening a binary as text file to get the extension logic fired --> To be discussed
- Overall test coverage using vscode-test is 78.87%
- dumper coverage using vscode-test is 81.03%
- Removing redundant cmake auto binary generating logic 

Examples:
- Updated to be compatiable with Ubuntu 20.04 objdump v2.38 as I faced some issues comparing the output of the extension preview, and the actual output in .objdump files

2024-08-24 17:06 UTC, eugeneo requested changes
Thank you, this is a great start.

Current goal (before we publish to a Marketplace) is to setup basics. We need to focus on code layout and basic conventions. Please do not waste your time on things like validation and error handling. We will better understand how it should be implemented once we have more functionality.

E.g. no need to check if `objdump` is available. Let its invocation fail naturally if it is not available.

From my experience, we may later decide to use the logic as a standalone library, e.g. to run it in the cloud. I suggest setting clear boundary. For example, build the `objdump` logic in `src/objdump` and never import anything VSCode specific there.

2024-08-25 14:35 UTC, aharbii commented on package.json
> +  },
Done

2024-08-25 14:36 UTC, aharbii commented on src/explore.ts
> +  await validateObjDumpBinary();
Done, removed to be only used onChangeconfiguration.

2024-08-25 14:36 UTC, aharbii commented on src/extension.ts
> +    console.log(`onDidOpenTextDocument: ${document.uri.fsPath}`);
Done, added it for testing, and escaped to the PR

2024-08-25 14:43 UTC, aharbii commented on src/extension.ts
> +      const isObjectFile = await preview.isObjectFile(document.fileName);
Done

2024-08-25 14:46 UTC, aharbii commented on src/objdump/dumper.ts
> +    args: string[],
Done

2024-08-25 14:46 UTC, aharbii commented on src/objdump/dumper.ts
> +    this.args = args;
Done

2024-08-25 15:52 UTC, aharbii commented on src/objdump/dumper.ts
> +    const {stdout, stderr} = await exec(command);
Done

2024-08-26 00:55 UTC, eugeneo reviewed
Thank you. I ran the code, looking great!

2024-08-26 00:55 UTC, eugeneo commented on package.json
> +            "default": "/usr/bin/objdump",
It looks like `spawn` uses $PATH
```suggestion
            "default": "objdump",
```

2024-08-26 00:55 UTC, eugeneo commented on src/explore.ts
> +    await handleConfigurationChange
"'await' has no effect on the type of this expression.ts(80007)"
```suggestion
    handleConfigurationChange
```

2024-08-26 00:55 UTC, eugeneo commented on src/explore.ts
> +    await handleStatusBarVisibility
```suggestion
    handleStatusBarVisibility
```

2024-08-26 00:55 UTC, eugeneo commented on src/explore.ts
> +
No need to check for the `objdump` existence separately. Version check will fail if it is not properly configured.

2024-08-26 00:55 UTC, eugeneo commented on src/preview.ts
> +}
Does not look like these are used.

2024-08-26 00:55 UTC, eugeneo commented on src/explore.ts
> +export class ObjDumpResult {
I think this should either be in a separate source file or in `preview.ts` as this class is not used in `explore.ts`

2024-08-26 00:55 UTC, eugeneo commented on src/objdump/dumper.ts
> +export async function execute(
As mentioned, I don't think there's a need to call `which objdump`, it is ok to communicate the failure to spawn the executable.

My suggestion is to to make `execute` and `getObjDumpVersion` members of `ObjDumper` class and call them on an instance.

2024-08-27 16:04 UTC, aharbii commented on src/explore.ts
> +
validateObjdumpPath, is not just for objdump existance type of errors, if the user enters a path of another valid executable for example "/usr/bin/gcc" no error will be shown for the user, that's the point of having such dump.isObjDumpBinary function, to avoid running any other executable on the object file rather than objdump itself

2024-08-27 16:04 UTC, aharbii commented on src/explore.ts
> +    await handleConfigurationChange
Done

2024-08-27 16:05 UTC, aharbii commented on src/explore.ts
> +    await handleStatusBarVisibility
Done

2024-08-27 16:10 UTC, aharbii commented on src/preview.ts
> +}
there where used in extension.ts, and was done that way to abstract the calling as the main design was to have everything GUI related in preview.ts, and any further logic for analysis or exploring the binary, parsing the ouput to be done in explore.ts

updated the design to have the analysis of the opened binary file main logic fire to be in preview.ts, and those functions to be removed.

2024-08-27 16:11 UTC, aharbii commented on package.json
> +            "default": "/usr/bin/objdump",
Done

2024-08-27 16:29 UTC, aharbii commented on src/explore.ts
> +export class ObjDumpResult {
I am planning to use this class with the planned functions to be in `explore.ts` to parse the objdump output, and provide the functions map to be displayed in the breadcrumb area later. 

also for the future plans, any non-GUI related analysis to be done on the output I suggest to be added here to avoid any complexity in `preview.ts`

2024-08-27 16:40 UTC, aharbii commented on src/objdump/dumper.ts
> +export async function execute(
Removed `which objdump` calls. 

the point of having `execute`, `getObjDumpVersion`, and `isObjDumpBinary` out of `ObjDumper`, is that they are used in `explore.ts` for validating the changed configuration, and updating the status bar.
cannot be done  without reworking the main design for explore.ts

2024-08-28 02:23 UTC, eugeneo approved these changes
Looks great! Feel free to merge when you are comfortable!

2024-08-28 02:23 UTC, eugeneo commented on src/explore.ts
> +export class ObjDumpResult {
Sounds good!

2024-08-28 02:23 UTC, eugeneo commented on src/objdump/dumper.ts
> +export async function execute(
Sounds good

2024-08-28 02:23 UTC, eugeneo commented on src/preview.ts
> +}
We need to avoid doing any work unless user actually opened an editor. This way we will not slow down the entire IDE.

2024-08-28 02:23 UTC, eugeneo commented on src/explore.ts
> +
That's ok. You can't really prevent a user from hurting themselves if they set their mind to it :)

Basically, no need to validate. Unparsed output will cause an error in editor and that's ok.

2024-08-28 02:23 UTC, eugeneo commented on src/extension.ts
>    const disposable = vscode.workspace.onDidOpenTextDocument(async document => {
Sounds good!

2024-08-28 18:44 UTC, merged