Adding function symbols provider logic
uchen-ml/codeart-binexplore pull request #31
Opened 2024-09-02 17:54 UTC by aharbii

- Adding function symbols provider logic
   - Disassembly of section (X) to be provided as parent
   -  ADDRESSES <X> to be provided as a child for the section
   - can be accessed from both, file outline, and breadcrumb area for the saved .uc files

- Adding initial language model to be used for syntax colors for both preview panel, and saved files
- Adding configuration for the user to configure saving .uc files automatically or not
- Auto saving CodeArt preview to .uc with the exact binary file name
   - the file is just saved for the user to reopen it, but whenever the user reopens the binary, it will be overwritten with the latest preview

2024-09-02 17:54 UTC, aharbii commented on src/objdump/dumper.ts
> +    const command = `${this.objDumpPath} ${this.args.join(' ')} ${this.filePath}`;
Just printing the command, the make easier for the user to identifiy the issue

2024-09-04 03:27 UTC, eugeneo requested changes
Looks great, only minor comments.

I published this executable: https://drive.google.com/file/d/1k0liI3W9PGsX4WAX6lgGNX5r5TjfnTc2/view?usp=drive_link - this is a benchmark for my ML framework (though this is debug build, slow) - feel free to try.

I also added `-C` (demangle) to my objdump flags and really happy with the result!

2024-09-04 03:27 UTC, eugeneo commented on src/explore.ts
> +    const match = text.match(/^[0-9a-f]+ <([^>]+)>:/);
This breaks parsing demangled C++, e.g. this line:
```
000000000000f46e <uchen::Parameters<8000008ul>::~Parameters()>:
```
```suggestion
    const match = text.match(/^[0-9a-f]+ <(.+)>:$/);
```

2024-09-04 03:27 UTC, eugeneo commented on src/objdump/dumper.ts
>          }
This and snippet below on lines 46-50 are same, should probably be a function.

2024-09-04 03:36 UTC, eugeneo commented
Just in case - release build: https://drive.google.com/file/d/1az7NBOlNms3VCKGll8kSew-DH-QN5LrY/view?usp=sharing

Just noticed the benchmark crashes with Segmentation Error :)

2024-09-04 03:37 UTC, eugeneo commented on syntaxes/language-uc-assembly.tmLanguage
> +            <string>\b(mov|add|sub|mul|div|and|or|xor|not|cmp|jmp|call|ret|push|movq|lea|movd|addq|setb|test|jne|leave|test|je|endbr64|bnd|nopl|nop|punpcklqdq|movaps|nopw|pop|cmpq|sar|jbe|movups|shl|
Note that this approach (hardcoding all assembly instructions) will not scale, will need a different approach. Current list does not include SIMD instructions and probably ARM instructions. Ignore this for now.

2024-09-04 16:30 UTC, aharbii commented on src/explore.ts
> +    const match = text.match(/^[0-9a-f]+ <([^>]+)>:/);
Done

2024-09-04 16:37 UTC, aharbii commented on src/explore.ts
> +    const match = text.match(/^[0-9a-f]+ <([^>]+)>:/);
Done

2024-09-04 16:37 UTC, aharbii commented on src/explore.ts
> +      );
Done, yes correct, most probably the crashed you faced comes from this point

2024-09-04 16:37 UTC, aharbii commented on src/explore.ts
> +    }
Done

2024-09-04 16:38 UTC, aharbii commented on src/objdump/dumper.ts
>          }
Done

2024-09-04 16:38 UTC, aharbii commented on syntaxes/language-uc-assembly.tmLanguage
> +            <string>\b(mov|add|sub|mul|div|and|or|xor|not|cmp|jmp|call|ret|push|movq|lea|movd|addq|setb|test|jne|leave|test|je|endbr64|bnd|nopl|nop|punpcklqdq|movaps|nopw|pop|cmpq|sar|jbe|movups|shl|
it's just an initial structure to be used later for syntax coloring

2024-09-04 16:42 UTC, aharbii commented
Thank you for sharing the binaries, I tested it also with -C to see how new regex behaves with demangled c++, and it's working fine. also updated the structure to only compare functions regex when it's only inside a section as proposed. 

also did minor refactoring for the constants to follow google typescript standards.

2024-09-06 01:24 UTC, eugeneo approved these changes
Looks great! Thanks. One real comment (about the negative offset). Feel free to merge!

2024-09-06 01:24 UTC, eugeneo commented on syntaxes/language-uc-assembly.tmLanguage
> +            <string>\b(mov|add|sub|mul|div|and|or|xor|not|cmp|jmp|call|ret|push|movq|lea|movd|addq|setb|test|jne|leave|test|je|endbr64|bnd|nopl|nop|punpcklqdq|movaps|nopw|pop|cmpq|sar|jbe|movups|shl|
Acknowledged! Excellent start. Highlights some ARM assembly 😀

2024-09-06 01:24 UTC, eugeneo commented on src/explore.ts
> +      text.match(SECTION_REGEX_1) || text.match(SECTION_REGEX_2);
My personal preference is to have RegExps inline, makes the code easier to follow.

Feel free to ignore the comment if you prefer to keep constants.

2024-09-06 14:07 UTC, aharbii commented on syntaxes/language-uc-assembly.tmLanguage
> +            <string>(;|#)[^\d].*$</string>
let's handle this while really working on the language model.

2024-09-06 14:09 UTC, aharbii commented on src/explore.ts
> +      text.match(SECTION_REGEX_1) || text.match(SECTION_REGEX_2);
I agree with you, but now as we have two functions uses those regex, in my humble opinion it will be easier to modify a constant than updating each function/line uses this regex.

2024-09-06 15:03 UTC, merged