Feature/auto_open_editor_on_click
uchen-ml/codeart-binexplore pull request #45
Opened 2024-09-27 11:28 UTC by aharbii

- Adding custom binary editor
    - The user now can select the configuration 'workbench.editor.defaultBinaryEditor' as 'codeart-binexplore.binaryEditor' and the CodeArt will be automatically displayed, bypassing the warning of editing a binary file

- Adding preview functionality
    - If the user chooses to keep the configuration 'workbench.editor.defaultBinaryEditor' as default, and opens the binaries with the default binary editor we can provide a preview option, besides the currently implemented auto-preview  in other editor
    - Within the explorer the user can right click a binary/object files, and select 'Preview CodeArt' option
    - If the active text editor is already a binary file in the native vscode text editor
        - Right click the file from the explorer and select 'Preview CodeArt'
        - From command palette, select 'Preview CodeArt' command for the active text file
        - From the editor title tab press on the 'CodeArt' icon to Preview CodeArt
        - Use keyboard shortcut 'ctrl+shift+v', 'cmd+shift+v' for previewing CodeArt for the active text file

2024-09-27 11:32 UTC, aharbii commented on src/preview.ts
> +    vscode.commands.executeCommand('workbench.action.closeActiveEditor');
After trying multiple approaches, I found that providing a textEditor will still pop-up the warning for editing a binary file with a text editor. Providing a custom editor with an HTML webview, will preview a readonly HTML content which cannot provide any symbols, or legit syntax coloring. 

Completely unseeing that the straight forward approach, was to close the opened customEditor, and open our already implemented CodeArt document as we have the actual binary uri.

2024-09-28 18:57 UTC, eugeneo requested changes
I do not have comments about the code just yet because I still see bad editor open experience.

I think you may need to ask for how to solve this problem on StackOverflow or GitHub. E.g. feel free to post on this thread - https://github.com/microsoft/vscode-discussions/discussions/1532#discussioncomment-10660169 - or ping [lramos15](https://github.com/lramos15) with the details.

2024-10-11 01:35 UTC, eugeneo approved these changes
Thanks. Looking great, I tested it locally.

Just in case, this is code review vocabulary I am used to (e.g. it is used by the teams I've been on):
`lgtm` - means "looking good to merge"
`nit` - optional comment, often a personal preference but not something that is important enough to block the merge.
`Ack` - (acknowledged) - means you comment was read and understood

2024-10-11 01:35 UTC, eugeneo commented on src/preview.ts
> +    return document;
nit

```suggestion
    return new CodeArtDocument(uri);
```

2024-10-11 01:35 UTC, eugeneo commented on src/preview.ts
> +    vscode.commands.executeCommand('workbench.action.closeActiveEditor');
Ack. Looks good.
The behavior seems smooth enough and is not on the primary path.

2024-10-11 01:35 UTC, eugeneo commented on src/preview.ts
> +  context.subscriptions.push(disposable);
nit: no need to use `disposable` variable. I believe that doing something like this makes code easier to read:
```suggestion
  context.subscriptions.push(
    vscode.workspace.onDidOpenTextDocument(analyzeOpenedDocument),
    vscode.commands.registerCommand(
      'codeart-binexplore.previewBinary',
      previewOutput
    ),
    vscode.workspace.registerTextDocumentContentProvider(
      EXTENSION_SCHEME,
      provider
    ),
    vscode.languages.registerDocumentSymbolProvider(
      {
        scheme: EXTENSION_SCHEME,
      },
      new CodeArtSymbolProvider()
    )
  );
```

2024-10-11 01:35 UTC, eugeneo commented on src/preview.ts
> +  vscode.window.registerCustomEditorProvider(
Proof that that `disposable` variable makes the code harder to read 😉 Looks like this should be added to the list of objects too.

2024-10-11 05:40 UTC, aharbii commented on src/preview.ts
> +    return document;
Done

2024-10-11 05:46 UTC, aharbii commented on src/preview.ts
> +  context.subscriptions.push(disposable);
I am ok with both, do not have specific preference. It would be good to standardize the development, so let's always go in the future with your recommended style.

2024-10-11 06:02 UTC, aharbii commented on src/preview.ts
> +  vscode.window.registerCustomEditorProvider(
I was thinking that we should always provide the custom editor for the user if they've chosen it as the default, so we don't interfere with their expected editor choice, even in case of failures. 'Getting an error when you open an application is better than unexpectedly not finding the application at all.'

However, on second thought, we shouldn't involve the user in our problems if the extension encounters a fatal failure. Pushing to the context subscriptions makes more sense. Thanks for making me rethink this hidden disaster! 😄

2024-10-13 00:36 UTC, eugeneo approved these changes
lgtm, feel free to merge

2024-10-13 01:09 UTC, merged